server:
  port: 8080

spring:
  application:
    name: producer-service

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb'      # In-Memory Mode
    # url: 'jdbc:h2:~/test'		# Embedded Mode
    user: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: ${KAFKA_PRODUCER_ACKS:all}


      # Producer Java 클래스의 패키지명을
      # Kafka Header에 기록하지 않는다.
      #
      # Producer와 Consumer가 서로 다른 Java 클래스를
      # 사용하기 때문에 코드 결합을 방지하기 위한 설정이다.
      properties:
        spring.json.add.type.headers: false
app:
  outbox:
    publisher:
      fixed-delay-ms: ${OUTBOX_PUBLISHER_FIXED_DELAY_MS:30000}
  kafka:
    topic:
      study-events: ${KAFKA_TOPIC_STUDY_EVENTS:study.message.created.v1}