services:
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    network_mode: host
    environment:
      SERVER_PORT: 8888
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: localhost:9092
    restart: unless-stopped